import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const SPA_DIR = resolve(process.cwd(), 'public/spa');
const OUTPUT_PATH = resolve(process.cwd(), 'src/app/[[...path]]/spaHtmlTemplates.ts');

async function run() {
  const html = await readFile(resolve(SPA_DIR, 'index.html'), 'utf8');

  const source = `// AUTO-GENERATED by scripts/buildSpaTemplates.ts
// DO NOT EDIT MANUALLY.
export const desktopHtmlTemplate = ${JSON.stringify(html)};
export const mobileHtmlTemplate = ${JSON.stringify(html)};
`;

  await writeFile(OUTPUT_PATH, source, 'utf8');
}

run().catch((error) => {
  console.error('Failed to generate SPA HTML templates:', error);
  process.exit(1);
});
